// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdverAckPro.proto

package cn.lfyun.network.message;

public final class AdverAck_Protocol {
  private AdverAck_Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AdverAckProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .NetProtocol.AdverAckItem item = 1;
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    java.util.List<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem> 
        getItemList();
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem getItem(int index);
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    java.util.List<? extends cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder> 
        getItemOrBuilderList();
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder getItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NetProtocol.AdverAckPro}
   */
  public static final class AdverAckPro extends
      com.google.protobuf.GeneratedMessage
      implements AdverAckProOrBuilder {
    // Use AdverAckPro.newBuilder() to construct.
    private AdverAckPro(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AdverAckPro(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AdverAckPro defaultInstance;
    public static AdverAckPro getDefaultInstance() {
      return defaultInstance;
    }

    public AdverAckPro getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AdverAckPro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                item_ = new java.util.ArrayList<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              item_.add(input.readMessage(cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckPro_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckPro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.class, cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.Builder.class);
    }

    public static com.google.protobuf.Parser<AdverAckPro> PARSER =
        new com.google.protobuf.AbstractParser<AdverAckPro>() {
      public AdverAckPro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdverAckPro(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AdverAckPro> getParserForType() {
      return PARSER;
    }

    // repeated .NetProtocol.AdverAckItem item = 1;
    public static final int ITEM_FIELD_NUMBER = 1;
    private java.util.List<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem> item_;
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    public java.util.List<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    public java.util.List<? extends cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
     */
    public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private void initFields() {
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetProtocol.AdverAckPro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.lfyun.network.message.AdverAck_Protocol.AdverAckProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckPro_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckPro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.class, cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.Builder.class);
      }

      // Construct using cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckPro_descriptor;
      }

      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro getDefaultInstanceForType() {
        return cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.getDefaultInstance();
      }

      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro build() {
        cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro buildPartial() {
        cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro result = new cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro(this);
        int from_bitField0_ = bitField0_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro) {
          return mergeFrom((cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro other) {
        if (other == cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro.getDefaultInstance()) return this;
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.lfyun.network.message.AdverAck_Protocol.AdverAckPro) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .NetProtocol.AdverAckItem item = 1;
      private java.util.List<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = new java.util.ArrayList<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem>(item_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder> itemBuilder_;

      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public java.util.List<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder setItem(
          int index, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder setItem(
          int index, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder addItem(cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder addItem(
          int index, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder addItem(
          cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder addItem(
          int index, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          super.addAll(values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public java.util.List<? extends cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.getDefaultInstance());
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.getDefaultInstance());
      }
      /**
       * <code>repeated .NetProtocol.AdverAckItem item = 1;</code>
       */
      public java.util.List<cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NetProtocol.AdverAckPro)
    }

    static {
      defaultInstance = new AdverAckPro(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetProtocol.AdverAckPro)
  }

  public interface AdverAckItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 contentType = 1;
    /**
     * <code>optional int32 contentType = 1;</code>
     */
    boolean hasContentType();
    /**
     * <code>optional int32 contentType = 1;</code>
     */
    int getContentType();

    // optional string contentName = 2;
    /**
     * <code>optional string contentName = 2;</code>
     */
    boolean hasContentName();
    /**
     * <code>optional string contentName = 2;</code>
     */
    java.lang.String getContentName();
    /**
     * <code>optional string contentName = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentNameBytes();

    // optional string content = 3;
    /**
     * <code>optional string content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code NetProtocol.AdverAckItem}
   */
  public static final class AdverAckItem extends
      com.google.protobuf.GeneratedMessage
      implements AdverAckItemOrBuilder {
    // Use AdverAckItem.newBuilder() to construct.
    private AdverAckItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AdverAckItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AdverAckItem defaultInstance;
    public static AdverAckItem getDefaultInstance() {
      return defaultInstance;
    }

    public AdverAckItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AdverAckItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              contentType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              contentName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.class, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder.class);
    }

    public static com.google.protobuf.Parser<AdverAckItem> PARSER =
        new com.google.protobuf.AbstractParser<AdverAckItem>() {
      public AdverAckItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdverAckItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AdverAckItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 contentType = 1;
    public static final int CONTENTTYPE_FIELD_NUMBER = 1;
    private int contentType_;
    /**
     * <code>optional int32 contentType = 1;</code>
     */
    public boolean hasContentType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 contentType = 1;</code>
     */
    public int getContentType() {
      return contentType_;
    }

    // optional string contentName = 2;
    public static final int CONTENTNAME_FIELD_NUMBER = 2;
    private java.lang.Object contentName_;
    /**
     * <code>optional string contentName = 2;</code>
     */
    public boolean hasContentName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string contentName = 2;</code>
     */
    public java.lang.String getContentName() {
      java.lang.Object ref = contentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contentName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contentName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentNameBytes() {
      java.lang.Object ref = contentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      contentType_ = 0;
      contentName_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, contentType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, contentType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetProtocol.AdverAckItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.lfyun.network.message.AdverAck_Protocol.AdverAckItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.class, cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.Builder.class);
      }

      // Construct using cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        contentType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        contentName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.lfyun.network.message.AdverAck_Protocol.internal_static_NetProtocol_AdverAckItem_descriptor;
      }

      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem getDefaultInstanceForType() {
        return cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.getDefaultInstance();
      }

      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem build() {
        cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem buildPartial() {
        cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem result = new cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contentType_ = contentType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contentName_ = contentName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem) {
          return mergeFrom((cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem other) {
        if (other == cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem.getDefaultInstance()) return this;
        if (other.hasContentType()) {
          setContentType(other.getContentType());
        }
        if (other.hasContentName()) {
          bitField0_ |= 0x00000002;
          contentName_ = other.contentName_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.lfyun.network.message.AdverAck_Protocol.AdverAckItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 contentType = 1;
      private int contentType_ ;
      /**
       * <code>optional int32 contentType = 1;</code>
       */
      public boolean hasContentType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 contentType = 1;</code>
       */
      public int getContentType() {
        return contentType_;
      }
      /**
       * <code>optional int32 contentType = 1;</code>
       */
      public Builder setContentType(int value) {
        bitField0_ |= 0x00000001;
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contentType = 1;</code>
       */
      public Builder clearContentType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contentType_ = 0;
        onChanged();
        return this;
      }

      // optional string contentName = 2;
      private java.lang.Object contentName_ = "";
      /**
       * <code>optional string contentName = 2;</code>
       */
      public boolean hasContentName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string contentName = 2;</code>
       */
      public java.lang.String getContentName() {
        java.lang.Object ref = contentName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          contentName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contentName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentNameBytes() {
        java.lang.Object ref = contentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contentName = 2;</code>
       */
      public Builder setContentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentName = 2;</code>
       */
      public Builder clearContentName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contentName_ = getDefaultInstance().getContentName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentName = 2;</code>
       */
      public Builder setContentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contentName_ = value;
        onChanged();
        return this;
      }

      // optional string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetProtocol.AdverAckItem)
    }

    static {
      defaultInstance = new AdverAckItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetProtocol.AdverAckItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetProtocol_AdverAckPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetProtocol_AdverAckPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetProtocol_AdverAckItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetProtocol_AdverAckItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021AdverAckPro.proto\022\013NetProtocol\"6\n\013Adve" +
      "rAckPro\022\'\n\004item\030\001 \003(\0132\031.NetProtocol.Adve" +
      "rAckItem\"I\n\014AdverAckItem\022\023\n\013contentType\030" +
      "\001 \001(\005\022\023\n\013contentName\030\002 \001(\t\022\017\n\007content\030\003 " +
      "\001(\tB.\n\027cn.lfyun.network.messageB\021AdverAck" +
      "_ProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetProtocol_AdverAckPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetProtocol_AdverAckPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetProtocol_AdverAckPro_descriptor,
              new java.lang.String[] { "Item", });
          internal_static_NetProtocol_AdverAckItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NetProtocol_AdverAckItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetProtocol_AdverAckItem_descriptor,
              new java.lang.String[] { "ContentType", "ContentName", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
