// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPropertyReqPro.proto

package cn.huizhi.car.pb.player;

public final class UserPropertyReq_Protocol {
  private UserPropertyReq_Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserPropertyReqProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 playerID = 1;
    /**
     * <code>optional int32 playerID = 1;</code>
     */
    boolean hasPlayerID();
    /**
     * <code>optional int32 playerID = 1;</code>
     */
    int getPlayerID();

    // optional int32 type = 2;
    /**
     * <code>optional int32 type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 2;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code NetProtocol.UserPropertyReqPro}
   */
  public static final class UserPropertyReqPro extends
      com.google.protobuf.GeneratedMessage
      implements UserPropertyReqProOrBuilder {
    // Use UserPropertyReqPro.newBuilder() to construct.
    private UserPropertyReqPro(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserPropertyReqPro(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserPropertyReqPro defaultInstance;
    public static UserPropertyReqPro getDefaultInstance() {
      return defaultInstance;
    }

    public UserPropertyReqPro getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserPropertyReqPro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.huizhi.car.pb.player.UserPropertyReq_Protocol.internal_static_NetProtocol_UserPropertyReqPro_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.huizhi.car.pb.player.UserPropertyReq_Protocol.internal_static_NetProtocol_UserPropertyReqPro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.class, cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.Builder.class);
    }

    public static com.google.protobuf.Parser<UserPropertyReqPro> PARSER =
        new com.google.protobuf.AbstractParser<UserPropertyReqPro>() {
      public UserPropertyReqPro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserPropertyReqPro(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserPropertyReqPro> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 playerID = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerID_;
    /**
     * <code>optional int32 playerID = 1;</code>
     */
    public boolean hasPlayerID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 playerID = 1;</code>
     */
    public int getPlayerID() {
      return playerID_;
    }

    // optional int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional int32 type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      playerID_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetProtocol.UserPropertyReqPro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.huizhi.car.pb.player.UserPropertyReq_Protocol.internal_static_NetProtocol_UserPropertyReqPro_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.huizhi.car.pb.player.UserPropertyReq_Protocol.internal_static_NetProtocol_UserPropertyReqPro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.class, cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.Builder.class);
      }

      // Construct using cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.huizhi.car.pb.player.UserPropertyReq_Protocol.internal_static_NetProtocol_UserPropertyReqPro_descriptor;
      }

      public cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro getDefaultInstanceForType() {
        return cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.getDefaultInstance();
      }

      public cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro build() {
        cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro buildPartial() {
        cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro result = new cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerID_ = playerID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro) {
          return mergeFrom((cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro other) {
        if (other == cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro.getDefaultInstance()) return this;
        if (other.hasPlayerID()) {
          setPlayerID(other.getPlayerID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.huizhi.car.pb.player.UserPropertyReq_Protocol.UserPropertyReqPro) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 playerID = 1;
      private int playerID_ ;
      /**
       * <code>optional int32 playerID = 1;</code>
       */
      public boolean hasPlayerID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 playerID = 1;</code>
       */
      public int getPlayerID() {
        return playerID_;
      }
      /**
       * <code>optional int32 playerID = 1;</code>
       */
      public Builder setPlayerID(int value) {
        bitField0_ |= 0x00000001;
        playerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerID = 1;</code>
       */
      public Builder clearPlayerID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 type = 2;
      private int type_ ;
      /**
       * <code>optional int32 type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetProtocol.UserPropertyReqPro)
    }

    static {
      defaultInstance = new UserPropertyReqPro(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetProtocol.UserPropertyReqPro)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetProtocol_UserPropertyReqPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetProtocol_UserPropertyReqPro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UserPropertyReqPro.proto\022\013NetProtocol\"" +
      "4\n\022UserPropertyReqPro\022\020\n\010playerID\030\001 \001(\005\022" +
      "\014\n\004type\030\002 \001(\005B5\n\027cn.huizhi.car.pb.player" +
      "B\030UserPropertyReq_ProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetProtocol_UserPropertyReqPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetProtocol_UserPropertyReqPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetProtocol_UserPropertyReqPro_descriptor,
              new java.lang.String[] { "PlayerID", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
