// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPropertyAckPro.proto

package cn.huizhi.car.pb.player;

public final class UserPropertyAck_Protocol {
  private UserPropertyAck_Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserPropertyAckProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 playerGrade = 1;
    /**
     * <code>optional int32 playerGrade = 1;</code>
     */
    boolean hasPlayerGrade();
    /**
     * <code>optional int32 playerGrade = 1;</code>
     */
    int getPlayerGrade();

    // optional int32 racerGrade = 2;
    /**
     * <code>optional int32 racerGrade = 2;</code>
     */
    boolean hasRacerGrade();
    /**
     * <code>optional int32 racerGrade = 2;</code>
     */
    int getRacerGrade();

    // optional string nickName = 3;
    /**
     * <code>optional string nickName = 3;</code>
     */
    boolean hasNickName();
    /**
     * <code>optional string nickName = 3;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>optional string nickName = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    // optional int32 sex = 4;
    /**
     * <code>optional int32 sex = 4;</code>
     */
    boolean hasSex();
    /**
     * <code>optional int32 sex = 4;</code>
     */
    int getSex();

    // optional int32 gold = 5;
    /**
     * <code>optional int32 gold = 5;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int32 gold = 5;</code>
     */
    int getGold();

    // optional int32 diamond = 6;
    /**
     * <code>optional int32 diamond = 6;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional int32 diamond = 6;</code>
     */
    int getDiamond();

    // optional int32 score = 7;
    /**
     * <code>optional int32 score = 7;</code>
     */
    boolean hasScore();
    /**
     * <code>optional int32 score = 7;</code>
     */
    int getScore();

    // optional string headTexture = 8;
    /**
     * <code>optional string headTexture = 8;</code>
     */
    boolean hasHeadTexture();
    /**
     * <code>optional string headTexture = 8;</code>
     */
    java.lang.String getHeadTexture();
    /**
     * <code>optional string headTexture = 8;</code>
     */
    com.google.protobuf.ByteString
        getHeadTextureBytes();

    // optional int32 proeExp = 9;
    /**
     * <code>optional int32 proeExp = 9;</code>
     */
    boolean hasProeExp();
    /**
     * <code>optional int32 proeExp = 9;</code>
     */
    int getProeExp();

    // optional int32 nextExp = 10;
    /**
     * <code>optional int32 nextExp = 10;</code>
     */
    boolean hasNextExp();
    /**
     * <code>optional int32 nextExp = 10;</code>
     */
    int getNextExp();

    // optional int32 curExp = 11;
    /**
     * <code>optional int32 curExp = 11;</code>
     */
    boolean hasCurExp();
    /**
     * <code>optional int32 curExp = 11;</code>
     */
    int getCurExp();
  }
  /**
   * Protobuf type {@code NetProtocol.UserPropertyAckPro}
   */
  public static final class UserPropertyAckPro extends
      com.google.protobuf.GeneratedMessage
      implements UserPropertyAckProOrBuilder {
    // Use UserPropertyAckPro.newBuilder() to construct.
    private UserPropertyAckPro(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserPropertyAckPro(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserPropertyAckPro defaultInstance;
    public static UserPropertyAckPro getDefaultInstance() {
      return defaultInstance;
    }

    public UserPropertyAckPro getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserPropertyAckPro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerGrade_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              racerGrade_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              nickName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sex_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gold_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              diamond_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              score_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              headTexture_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              proeExp_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              nextExp_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              curExp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.huizhi.car.pb.player.UserPropertyAck_Protocol.internal_static_NetProtocol_UserPropertyAckPro_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.huizhi.car.pb.player.UserPropertyAck_Protocol.internal_static_NetProtocol_UserPropertyAckPro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.class, cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.Builder.class);
    }

    public static com.google.protobuf.Parser<UserPropertyAckPro> PARSER =
        new com.google.protobuf.AbstractParser<UserPropertyAckPro>() {
      public UserPropertyAckPro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserPropertyAckPro(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserPropertyAckPro> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 playerGrade = 1;
    public static final int PLAYERGRADE_FIELD_NUMBER = 1;
    private int playerGrade_;
    /**
     * <code>optional int32 playerGrade = 1;</code>
     */
    public boolean hasPlayerGrade() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 playerGrade = 1;</code>
     */
    public int getPlayerGrade() {
      return playerGrade_;
    }

    // optional int32 racerGrade = 2;
    public static final int RACERGRADE_FIELD_NUMBER = 2;
    private int racerGrade_;
    /**
     * <code>optional int32 racerGrade = 2;</code>
     */
    public boolean hasRacerGrade() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 racerGrade = 2;</code>
     */
    public int getRacerGrade() {
      return racerGrade_;
    }

    // optional string nickName = 3;
    public static final int NICKNAME_FIELD_NUMBER = 3;
    private java.lang.Object nickName_;
    /**
     * <code>optional string nickName = 3;</code>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string nickName = 3;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 sex = 4;
    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>optional int32 sex = 4;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 sex = 4;</code>
     */
    public int getSex() {
      return sex_;
    }

    // optional int32 gold = 5;
    public static final int GOLD_FIELD_NUMBER = 5;
    private int gold_;
    /**
     * <code>optional int32 gold = 5;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 gold = 5;</code>
     */
    public int getGold() {
      return gold_;
    }

    // optional int32 diamond = 6;
    public static final int DIAMOND_FIELD_NUMBER = 6;
    private int diamond_;
    /**
     * <code>optional int32 diamond = 6;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 diamond = 6;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    // optional int32 score = 7;
    public static final int SCORE_FIELD_NUMBER = 7;
    private int score_;
    /**
     * <code>optional int32 score = 7;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 score = 7;</code>
     */
    public int getScore() {
      return score_;
    }

    // optional string headTexture = 8;
    public static final int HEADTEXTURE_FIELD_NUMBER = 8;
    private java.lang.Object headTexture_;
    /**
     * <code>optional string headTexture = 8;</code>
     */
    public boolean hasHeadTexture() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string headTexture = 8;</code>
     */
    public java.lang.String getHeadTexture() {
      java.lang.Object ref = headTexture_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headTexture_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string headTexture = 8;</code>
     */
    public com.google.protobuf.ByteString
        getHeadTextureBytes() {
      java.lang.Object ref = headTexture_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headTexture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 proeExp = 9;
    public static final int PROEEXP_FIELD_NUMBER = 9;
    private int proeExp_;
    /**
     * <code>optional int32 proeExp = 9;</code>
     */
    public boolean hasProeExp() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 proeExp = 9;</code>
     */
    public int getProeExp() {
      return proeExp_;
    }

    // optional int32 nextExp = 10;
    public static final int NEXTEXP_FIELD_NUMBER = 10;
    private int nextExp_;
    /**
     * <code>optional int32 nextExp = 10;</code>
     */
    public boolean hasNextExp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 nextExp = 10;</code>
     */
    public int getNextExp() {
      return nextExp_;
    }

    // optional int32 curExp = 11;
    public static final int CUREXP_FIELD_NUMBER = 11;
    private int curExp_;
    /**
     * <code>optional int32 curExp = 11;</code>
     */
    public boolean hasCurExp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 curExp = 11;</code>
     */
    public int getCurExp() {
      return curExp_;
    }

    private void initFields() {
      playerGrade_ = 0;
      racerGrade_ = 0;
      nickName_ = "";
      sex_ = 0;
      gold_ = 0;
      diamond_ = 0;
      score_ = 0;
      headTexture_ = "";
      proeExp_ = 0;
      nextExp_ = 0;
      curExp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerGrade_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, racerGrade_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, gold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, diamond_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, score_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getHeadTextureBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, proeExp_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, nextExp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, curExp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerGrade_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, racerGrade_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, gold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, diamond_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, score_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getHeadTextureBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, proeExp_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, nextExp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, curExp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetProtocol.UserPropertyAckPro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.huizhi.car.pb.player.UserPropertyAck_Protocol.internal_static_NetProtocol_UserPropertyAckPro_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.huizhi.car.pb.player.UserPropertyAck_Protocol.internal_static_NetProtocol_UserPropertyAckPro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.class, cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.Builder.class);
      }

      // Construct using cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        racerGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        headTexture_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        proeExp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        nextExp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        curExp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.huizhi.car.pb.player.UserPropertyAck_Protocol.internal_static_NetProtocol_UserPropertyAckPro_descriptor;
      }

      public cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro getDefaultInstanceForType() {
        return cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.getDefaultInstance();
      }

      public cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro build() {
        cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro buildPartial() {
        cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro result = new cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerGrade_ = playerGrade_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.racerGrade_ = racerGrade_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.diamond_ = diamond_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.headTexture_ = headTexture_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.proeExp_ = proeExp_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.nextExp_ = nextExp_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.curExp_ = curExp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro) {
          return mergeFrom((cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro other) {
        if (other == cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro.getDefaultInstance()) return this;
        if (other.hasPlayerGrade()) {
          setPlayerGrade(other.getPlayerGrade());
        }
        if (other.hasRacerGrade()) {
          setRacerGrade(other.getRacerGrade());
        }
        if (other.hasNickName()) {
          bitField0_ |= 0x00000004;
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasHeadTexture()) {
          bitField0_ |= 0x00000080;
          headTexture_ = other.headTexture_;
          onChanged();
        }
        if (other.hasProeExp()) {
          setProeExp(other.getProeExp());
        }
        if (other.hasNextExp()) {
          setNextExp(other.getNextExp());
        }
        if (other.hasCurExp()) {
          setCurExp(other.getCurExp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.huizhi.car.pb.player.UserPropertyAck_Protocol.UserPropertyAckPro) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 playerGrade = 1;
      private int playerGrade_ ;
      /**
       * <code>optional int32 playerGrade = 1;</code>
       */
      public boolean hasPlayerGrade() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 playerGrade = 1;</code>
       */
      public int getPlayerGrade() {
        return playerGrade_;
      }
      /**
       * <code>optional int32 playerGrade = 1;</code>
       */
      public Builder setPlayerGrade(int value) {
        bitField0_ |= 0x00000001;
        playerGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerGrade = 1;</code>
       */
      public Builder clearPlayerGrade() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerGrade_ = 0;
        onChanged();
        return this;
      }

      // optional int32 racerGrade = 2;
      private int racerGrade_ ;
      /**
       * <code>optional int32 racerGrade = 2;</code>
       */
      public boolean hasRacerGrade() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 racerGrade = 2;</code>
       */
      public int getRacerGrade() {
        return racerGrade_;
      }
      /**
       * <code>optional int32 racerGrade = 2;</code>
       */
      public Builder setRacerGrade(int value) {
        bitField0_ |= 0x00000002;
        racerGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 racerGrade = 2;</code>
       */
      public Builder clearRacerGrade() {
        bitField0_ = (bitField0_ & ~0x00000002);
        racerGrade_ = 0;
        onChanged();
        return this;
      }

      // optional string nickName = 3;
      private java.lang.Object nickName_ = "";
      /**
       * <code>optional string nickName = 3;</code>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string nickName = 3;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickName = 3;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickName = 3;</code>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickName = 3;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickName_ = value;
        onChanged();
        return this;
      }

      // optional int32 sex = 4;
      private int sex_ ;
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sex = 4;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gold = 5;
      private int gold_ ;
      /**
       * <code>optional int32 gold = 5;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 gold = 5;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>optional int32 gold = 5;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000010;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gold = 5;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gold_ = 0;
        onChanged();
        return this;
      }

      // optional int32 diamond = 6;
      private int diamond_ ;
      /**
       * <code>optional int32 diamond = 6;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 diamond = 6;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional int32 diamond = 6;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000020;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 diamond = 6;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000020);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // optional int32 score = 7;
      private int score_ ;
      /**
       * <code>optional int32 score = 7;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 score = 7;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 7;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000040;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 7;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000040);
        score_ = 0;
        onChanged();
        return this;
      }

      // optional string headTexture = 8;
      private java.lang.Object headTexture_ = "";
      /**
       * <code>optional string headTexture = 8;</code>
       */
      public boolean hasHeadTexture() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string headTexture = 8;</code>
       */
      public java.lang.String getHeadTexture() {
        java.lang.Object ref = headTexture_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          headTexture_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string headTexture = 8;</code>
       */
      public com.google.protobuf.ByteString
          getHeadTextureBytes() {
        java.lang.Object ref = headTexture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headTexture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string headTexture = 8;</code>
       */
      public Builder setHeadTexture(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        headTexture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string headTexture = 8;</code>
       */
      public Builder clearHeadTexture() {
        bitField0_ = (bitField0_ & ~0x00000080);
        headTexture_ = getDefaultInstance().getHeadTexture();
        onChanged();
        return this;
      }
      /**
       * <code>optional string headTexture = 8;</code>
       */
      public Builder setHeadTextureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        headTexture_ = value;
        onChanged();
        return this;
      }

      // optional int32 proeExp = 9;
      private int proeExp_ ;
      /**
       * <code>optional int32 proeExp = 9;</code>
       */
      public boolean hasProeExp() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 proeExp = 9;</code>
       */
      public int getProeExp() {
        return proeExp_;
      }
      /**
       * <code>optional int32 proeExp = 9;</code>
       */
      public Builder setProeExp(int value) {
        bitField0_ |= 0x00000100;
        proeExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 proeExp = 9;</code>
       */
      public Builder clearProeExp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        proeExp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 nextExp = 10;
      private int nextExp_ ;
      /**
       * <code>optional int32 nextExp = 10;</code>
       */
      public boolean hasNextExp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 nextExp = 10;</code>
       */
      public int getNextExp() {
        return nextExp_;
      }
      /**
       * <code>optional int32 nextExp = 10;</code>
       */
      public Builder setNextExp(int value) {
        bitField0_ |= 0x00000200;
        nextExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 nextExp = 10;</code>
       */
      public Builder clearNextExp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        nextExp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 curExp = 11;
      private int curExp_ ;
      /**
       * <code>optional int32 curExp = 11;</code>
       */
      public boolean hasCurExp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 curExp = 11;</code>
       */
      public int getCurExp() {
        return curExp_;
      }
      /**
       * <code>optional int32 curExp = 11;</code>
       */
      public Builder setCurExp(int value) {
        bitField0_ |= 0x00000400;
        curExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 curExp = 11;</code>
       */
      public Builder clearCurExp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        curExp_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetProtocol.UserPropertyAckPro)
    }

    static {
      defaultInstance = new UserPropertyAckPro(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetProtocol.UserPropertyAckPro)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetProtocol_UserPropertyAckPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetProtocol_UserPropertyAckPro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UserPropertyAckPro.proto\022\013NetProtocol\"" +
      "\321\001\n\022UserPropertyAckPro\022\023\n\013playerGrade\030\001 " +
      "\001(\005\022\022\n\nracerGrade\030\002 \001(\005\022\020\n\010nickName\030\003 \001(" +
      "\t\022\013\n\003sex\030\004 \001(\005\022\014\n\004gold\030\005 \001(\005\022\017\n\007diamond\030" +
      "\006 \001(\005\022\r\n\005score\030\007 \001(\005\022\023\n\013headTexture\030\010 \001(" +
      "\t\022\017\n\007proeExp\030\t \001(\005\022\017\n\007nextExp\030\n \001(\005\022\016\n\006c" +
      "urExp\030\013 \001(\005B5\n\027cn.huizhi.car.pb.playerB\030" +
      "UserPropertyAck_ProtocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetProtocol_UserPropertyAckPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetProtocol_UserPropertyAckPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetProtocol_UserPropertyAckPro_descriptor,
              new java.lang.String[] { "PlayerGrade", "RacerGrade", "NickName", "Sex", "Gold", "Diamond", "Score", "HeadTexture", "ProeExp", "NextExp", "CurExp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
